### ISSUE TITLE
Need images

### ISSUE THREAD

**Issue by chrir0** [robinmdm/assignment-2a#1]
Need images for continent selection
Need image for later page that shows university (as example BTU)
Need image for first page (maybe icon + "Pathfinder" text in some nice font?)
Need images of a door or something like in the diagram for selecting field

**Comment by robinmdm** [comment]
On it

**Comment by robinmdm** [comment]
should these images be in svg format?

**Comment by robinmdm** [comment]
I have made -
   a folder for continent named Continent Images
   a folder for university named University Images
   added door image and pathfinder text with a nice font
