### ISSUE TITLE
Homepage prototype

### ISSUE THREAD

**Issue by noerenil** [robinmdm/assignment-2a#3]
We finished a prototype of the homepage based on your directives.
As the assignment requires, we're now asking for your approval of the prototype before we can continue implementing the website. If something is not to your liking, we can still easily change it since this is just a prototype.

You can find our prototype in the folder `assignment-2b-group5`.

**Comment by robinmdm** [comment]
Yes, it is okay, you can proceed further and implement the rest. For any possible queries, feel free to ask accordingly.
