### ISSUE TITLE
Image for the About Us Page

### ISSUE THREAD

**Issue by jrobmey** [robinmdm/assignment-2a#5]
Hey there!
In your Webpages List you provided a link to an image we should use. However this link leads to a stockphoto site where you have to purchase a license in order to use the images.
Should we just use the watermarked preview or if not please provide a new image that we can use.
Thank you in advance.

**Comment by robinmdm** [comment]
Hello

You can use the watermarked preview. Also, you can edit or add any image of your liking.

There would be no problem with that. Thank You!!

**Comment by jrobmey** [comment]
Alright, I'll just use the preview image. 
Thanks!
