### ISSUE TITLE
Design suggestion header/footer

### ISSUE THREAD

**Issue by noerenil** [robinmdm/assignment-2a#6]
While working on the website we noticed that it can be hard to distinguish the header and footer from the rest of the page. Therefore we tried to make those elements stand out by giving them your alternate accent color. (a screenshot is attached to this issue)

Now we want to ask you what you think about it. Should we keep it this way or revert back to the original prototype?

<img width="1680" alt="grafik" src="https://user-images.githubusercontent.com/117810210/211304273-2eb93628-51df-40e1-a0df-f66b1649753e.png">

**Comment by robinmdm** [comment]
Hello There! The header color should have some gradient matched with the footer color. we do not have the problem with the design, just try to apply the color which suits with the header color.

Thank you for your query! Let us know if you have any more queries.

**Comment by noerenil** [comment]
The footer currently has the same color as the header. What do you mean by gradient? Which direction should it have and what colors? And how should it be matched with the footer color?

**Comment by robinmdm** [comment]
@chrir0 , please answer their query and give them an appropriate answer.

**Comment by chrir0** [comment]
@noerenil We like that design choice you made and accept it, don't worry about the further inquiry!
